version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "9874:9874"
    depends_on:
      - mongodb
    environment:
      DATABASE_URL: "mongodb://mongodb:27017/"

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  mongo-data:
